tabs instead of spaces

diff --git a/create-manifest b/create-manifest
--- a/create-manifest
+++ b/create-manifest
@@ -21,84 +21,84 @@ homepage=
 
 usage()
 {
-  cat <<USAGE
+	cat <<USAGE
 
 Create an image manifest from a given image file
 
 Usage:
-  $0 -f <filename> -k <kernel_version> -m <min_platform> -n <name> -v <version>
+	$0 -f <filename> -k <kernel_version> -m <min_platform> -n <name> -v <version>
 
 OPTIONS:
-  -d <image description> (optional, default: "<NAME> <VERSION> VM Image")
-  -f <filename of VM image> (required)
-  -k <kernel version for the VM image> (required)
-  -m <min_platform> (required)
-  -n <name of VM image> (required)
-  -o <the os of VM image> (optional, default: "other")
-  -v <version of VM image> (required)
-  -h <homepage link> (optional)
+	-d <image description> (optional, default: "<NAME> <VERSION> VM Image")
+	-f <filename of VM image> (required)
+	-k <kernel version for the VM image> (required)
+	-m <min_platform> (required)
+	-n <name of VM image> (required)
+	-o <the os of VM image> (optional, default: "other")
+	-v <version of VM image> (required)
+	-h <homepage link> (optional)
 
 Example:
 
-  $0 -f fedora-22-20150801.zfs.gz -k 4.0.4 -m 20150801T201553Z -n fedora22 -v 20150801
+	$0 -f fedora-22-20150801.zfs.gz -k 4.0.4 -m 20150801T201553Z -n fedora22 -v 20150801
 
 USAGE
-    exit 1
+	exit 1
 }
 
 while getopts d:f:k:m:n:o:v:h:? OPTION
 do
-  case $OPTION in
-  d)
-      description=${OPTARG}
-      ;;
-  f)
-      filename=${OPTARG}
-      ;;
-  k)
-      kernel=${OPTARG}
-      ;;
-  m)
-      min_platform=${OPTARG}
-      ;;
-  n)
-      name=${OPTARG}
-      ;;
-  o)
-      os=${OPTARG}
-      ;;
-  v)
-      version=${OPTARG}
-      ;;
-  h)
-      homepage=${OPTARG}
-      ;;
-  \?)
-      usage
-      ;;
-  esac
+	case $OPTION in
+	d)
+		description=${OPTARG}
+		;;
+	f)
+		filename=${OPTARG}
+		;;
+	k)
+		kernel=${OPTARG}
+		;;
+	m)
+		 min_platform=${OPTARG}
+		 ;;
+	n)
+		name=${OPTARG}
+		;;
+	o)
+		os=${OPTARG}
+		;;
+	v)
+		version=${OPTARG}
+		;;
+	h)
+		homepage=${OPTARG}
+		;;
+	\?)
+		usage
+		;;
+	esac
 done
 
 if [[ -z ${filename} || -z ${kernel} || -z ${min_platform} || -z ${name} || -z ${version} ]]; then
-  echo "FATAL: All of -f, -k, -m, -n and -v are required."
-  usage
+	echo "FATAL: All of -f, -k, -m, -n and -v are required."
+	usage
 fi
 
 if [[ -z ${description} ]]; then
-  description="${name} ${version} LX-brand image"
+	description="${name} ${version} LX-brand image"
 fi
 
 if [[ -z ${os} ]]; then
-  os="other"
+	os="other"
 fi
 
 if [[ -z ${homepage} ]]; then
-  homepage=https://docs.joyent.com/images
+	homepage=https://docs.joyent.com/images
 fi
 
 if [[ ! -f ${filename} ]]; then
-  echo "FATAL: ${filename} does not exist."
-  usage
+	echo "FATAL: ${filename} does not exist."
+	usage
 fi
 
 shasum=$($SUM -x sha1 ${filename} | cut -d' ' -f1)
@@ -106,40 +106,40 @@ filesize=$(wc -c < ${filename})
 
 cat <<EOF
 {
-  "v": "2",
-  "name": "${name}",
-  "version": "${version}",
-  "type": "lx-dataset",
-  "description": "${description}",
-  "homepage": "${homepage}",
-  "published_at": "${now}",
-  "os": "${os}",
-  "files": [
-    {
-      "sha1": "${shasum}",
-      "size": ${filesize},
-      "compression": "gzip"
-    }
-  ],
-  "requirements": {
-    "networks": [
-      {
-        "name": "net0",
-        "description": "public"
-      }
-    ],
-    "min_platform": {
-         "7.0": "${min_platform}"
-       },
-    "brand": "lx"
-  },
-  "uuid": "${vm_uuid}",
-  "public": false,
-  "owner": "00000000-0000-0000-0000-000000000000",
-  "tags": {
-    "role": "os",
-    "kernel_version": "${kernel}"
-  }
+	"v": "2",
+	"name": "${name}",
+	"version": "${version}",
+	"type": "lx-dataset",
+	"description": "${description}",
+	"homepage": "${homepage}",
+	"published_at": "${now}",
+	"os": "${os}",
+	"files": [
+		{
+			"sha1": "${shasum}",
+			"size": ${filesize},
+			"compression": "gzip"
+		}
+	],
+	"requirements": {
+		"networks": [
+			{
+				"name": "net0",
+				"description": "public"
+			}
+		],
+		"min_platform": {
+			"7.0": "${min_platform}"
+		},
+		"brand": "lx"
+	},
+	"uuid": "${vm_uuid}",
+	"public": false,
+	"owner": "00000000-0000-0000-0000-000000000000",
+	"tags": {
+		"role": "os",
+		"kernel_version": "${kernel}"
+	}
 }
 EOF
 
diff --git a/install b/install
--- a/install
+++ b/install
@@ -18,21 +18,21 @@ cat <<EOF
 Install and modify Fedora in a given directory in a given directory using a given mirror
 
 Usage:
-  $0 -d <INSTALL_DIR> -m <MIRROR> -R <RELEASE> -r <RELEASE_PACKAGE> -i <IMAGE_NAME> -p <NAME> -D <DESC> -u <DOCS>
+	$0 -d <INSTALL_DIR> -m <MIRROR> -R <RELEASE> -r <RELEASE_PACKAGE> -i <IMAGE_NAME> -p <NAME> -D <DESC> -u <DOCS>
 
 Example:
-  $0 -d /data/chroot -m http://fedora.bhs.mirrors.ovh.net/linux/releases/22/Server/x86_64/os/Packages/f -r fedora-release-22-1.noarch.rpm -i fedora-22 -p "Fedora 22 LX Brand" -D "Fedora 64-bit lx-brand image." -u https://docs.joyent.com/images/container-native-linux
+	$0 -d /data/chroot -m http://fedora.bhs.mirrors.ovh.net/linux/releases/22/Server/x86_64/os/Packages/f -r fedora-release-22-1.noarch.rpm -i fedora-22 -p "Fedora 22 LX Brand" -D "Fedora 64-bit lx-brand image." -u https://docs.joyent.com/images/container-native-linux
 
 OPTIONS:
-  -d A path to the install directory
-  -m A URL for the desired archive mirror
-  -R The release of Fedora (e.g. 22)
-  -r The release package used for installing Fedora
-  -i The name of the image. This is used for naming the tarball. 
-  -p The proper name of the image. Use quotes. This is used in the MOTD and /etc/product file.
-  -D A description for the image. This is used in the image manifest and the /etc/product file.
-  -u A URL to the image docs [optional]
-  -h Show this message
+	-d A path to the install directory
+	-m A URL for the desired archive mirror
+	-R The release of Fedora (e.g. 22)
+	-r The release package used for installing Fedora
+	-i The name of the image. This is used for naming the tarball. 
+	-p The proper name of the image. Use quotes. This is used in the MOTD and /etc/product file.
+	-D A description for the image. This is used in the image manifest and the /etc/product file.
+	-u A URL to the image docs [optional]
+	-h Show this message
 
 EOF
 }
@@ -48,100 +48,100 @@ DOCS=
 
 while getopts "hd:m:R:r:i:p:D:u:" OPTION
 do
-  case $OPTION in
-    h)
-      usage
-      exit
-      ;;
-    d)
-      INSTALL_DIR=${OPTARG%/}
-      ;;
-    m)
-      MIRROR=${OPTARG}
-      ;;
-    R)
-      RELEASE=${OPTARG}
-      ;;
-    r)
-      RELEASE_PACKAGE=${OPTARG}
-      ;;
-    i)
-      IMAGE_NAME=${OPTARG}
-      ;;
-    p)
-      NAME=${OPTARG}
-      ;;
-    D)
-      DESC=${OPTARG}
-      ;;
-    u)
-      DOCS=${OPTARG}
-      ;;
-    \?)
-      usage
-      exit
-      ;;
-  esac
+	case $OPTION in
+		h)
+			usage
+			exit
+			;;
+		d)
+			INSTALL_DIR=${OPTARG%/}
+			;;
+		m)
+			MIRROR=${OPTARG}
+			;;
+		R)
+			RELEASE=${OPTARG}
+			;;
+		r)
+			RELEASE_PACKAGE=${OPTARG}
+			;;
+		i)
+			IMAGE_NAME=${OPTARG}
+			;;
+		p)
+			NAME=${OPTARG}
+			;;
+		D)
+			DESC=${OPTARG}
+			;;
+		u)
+			DOCS=${OPTARG}
+			;;
+		\?)
+			usage
+			exit
+			;;
+	esac
 done
 
 if [[ $# -eq 0 ]]; then
-  usage
-  exit 1
+	usage
+	exit 1
 fi
 
 if [[ ! -e ${INSTALL_DIR} ]] ; then
-  echo "Directory $INSTALL_DIR not found"
-  exit 1
+	echo "Directory $INSTALL_DIR not found"
+	exit 1
 fi
 
 if [[ -z ${INSTALL_DIR} ]]; then
-  echo "Error: missing install directory (-d) value"
-  exit 1
+	echo "Error: missing install directory (-d) value"
+	exit 1
 fi
 
 if [[ -z ${MIRROR} ]]; then
-  echo "Error: missing mirror (-m) value"
-  exit 1
+	echo "Error: missing mirror (-m) value"
+	exit 1
 fi
 
 if [[ -z ${RELEASE} ]]; then
-  echo "Error: missing release (-R) value"
-  exit 1
+	echo "Error: missing release (-R) value"
+	exit 1
 fi
 
 if [[ -z ${RELEASE_PACKAGE} ]]; then
-  echo "Error: missing release package (-r) value"
-  exit 1
+	echo "Error: missing release package (-r) value"
+	exit 1
 fi
 
 if [[ -z ${IMAGE_NAME} ]]; then
-  echo "Error: missing image name (-i) value"
-  exit 1
+	echo "Error: missing image name (-i) value"
+	exit 1
 fi
 
 if [[ -z ${NAME} ]]; then
-  echo "Error: missing proper name (-p) value"
-  exit 1
+	echo "Error: missing proper name (-p) value"
+	exit 1
 fi
 
 if [[ -z ${DESC} ]]; then
-  echo "Error: missing image description (-D) value"
-  exit 1
+	echo "Error: missing image description (-D) value"
+	exit 1
 fi
 
 TARGET="${IMAGE_NAME}-${BUILD_DATE}.tar.gz"
 
 if [[ -z ${DOCS} ]]; then
-  DOCS="https://docs.joyent.com/images/container-native-linux"
+	DOCS="https://docs.joyent.com/images/container-native-linux"
 fi
 
 echo "==> Installing Fedora into $INSTALL_DIR"
 
 if [[ -d $INSTALL_DIR ]]; then
-  echo "====> Found previous chroot. Deleting and creating a new one."
-  rm -rf $INSTALL_DIR
-  mkdir -p $INSTALL_DIR
-  mkdir -p $INSTALL_DIR/var/lib/rpm
+	echo "====> Found previous chroot. Deleting and creating a new one."
+	rm -rf $INSTALL_DIR
+	mkdir -p $INSTALL_DIR
+	mkdir -p $INSTALL_DIR/var/lib/rpm
 fi
 
 rpm --root=$INSTALL_DIR --initdb
@@ -166,14 +166,14 @@ set +e
 KEYS=( 81B46521 FDB19C98 64DAB85D )
 
 for KEY in "${KEYS[@]}"; do
-  # ${VAR_NAME,,} converts to lowercase
-  rpm -qi gpg-pubkey-${KEY,,} > /dev/null
-  if [[ $? -gt 0 ]]; then
-      echo "===> Adding gpg signing keys $KEY"
-      curl -sSLO https://getfedora.org/static/$KEY.txt
-      rpm --import $KEY.txt
-      rm -rf $KEY.txt
-  fi
+	# ${VAR_NAME,,} converts to lowercase
+	rpm -qi gpg-pubkey-${KEY,,} > /dev/null
+	if [[ $? -gt 0 ]]; then
+		echo "===> Adding gpg signing keys $KEY"
+		curl -sSLO https://getfedora.org/static/$KEY.txt
+		rpm --import $KEY.txt
+		rm -rf $KEY.txt
+	fi
 done
 set -e
 
@@ -184,14 +184,14 @@ dnf --installroot=$INSTALL_DIR --releasever=$RELEASE install -y /var/tmp/$RELEAS
 
 echo "==> Installing Fedora Server Edition group..."
 dnf --installroot=$INSTALL_DIR \
-      --setopt=group_package_types=default,mandatory \
-      --exclude=abrt-addon* \
-      --exclude=abrt-cli \
-      --exclude=dracut-config-rescue \
-      --exclude=kernel-devel \
-      --exclude=kernel-headers \
-      --exclude=plymouth* \
-      group -y install "Fedora Server Edition"
+	--setopt=group_package_types=default,mandatory \
+	--exclude=abrt-addon* \
+	--exclude=abrt-cli \
+	--exclude=dracut-config-rescue \
+	--exclude=kernel-devel \
+	--exclude=kernel-headers \
+	--exclude=plymouth* \
+	group -y install "Fedora Server Edition"
 
 echo "==> Installing additional packages..."
 dnf --installroot=$INSTALL_DIR install -y gettext vim-enhanced
@@ -207,7 +207,7 @@ rm -rf /var/tmp/$RELEASE_PACKAGE
 
 echo "==> Setting TZ to UTC"
 if [[ -f $INSTALL_DIR/etc/localtime ]]; then
-  rm $INSTALL_DIR/etc/localtime
+	rm $INSTALL_DIR/etc/localtime
 fi
 
 cp $INSTALL_DIR/usr/share/zoneinfo/UTC $INSTALL_DIR/etc/localtime
@@ -218,8 +218,8 @@ echo "LANG=\"en_US.UTF-8\"" > $INSTALL_DIR/etc/locale.conf
 # Systemd overrides for systemd-timedated and systemd-hostnamed
 #
 # See:
-#   - https://github.com/joyent/centos-lx-brand-image-builder/issues/5
-#   - https://smartos.org/bugview/OS-5304
+# 	- https://github.com/joyent/centos-lx-brand-image-builder/issues/5
+# 	- https://smartos.org/bugview/OS-5304
 #
 # TODO: This should be removed when the relevant cgroup etc support is in
 # the platform.
@@ -227,10 +227,10 @@ SERVICES=( systemd-hostnamed systemd-localed systemd-timedated timedatex )
 
 for SERVICE in "${SERVICES[@]}"; do
 	echo "==> Adding systemd overrides for: $SERVICE"
-  OVERRIDE_DIR=$INSTALL_DIR/etc/systemd/system/${SERVICE}.service.d
-  mkdir -p $OVERRIDE_DIR
+	OVERRIDE_DIR=$INSTALL_DIR/etc/systemd/system/${SERVICE}.service.d
+	mkdir -p $OVERRIDE_DIR
 
-  cat << OVERRIDE > ${OVERRIDE_DIR}/override.conf
+	cat << OVERRIDE > ${OVERRIDE_DIR}/override.conf
 [Service]
 PrivateTmp=no
 PrivateDevices=no
@@ -244,10 +244,10 @@ SERVICES=( httpd )
 
 for SERVICE in "${SERVICES[@]}"; do
 	echo "==> Adding systemd overrides for: $SERVICE"
-  OVERRIDE_DIR=$INSTALL_DIR/etc/systemd/system/${SERVICE}.service.d
-  mkdir -p $OVERRIDE_DIR
+	OVERRIDE_DIR=$INSTALL_DIR/etc/systemd/system/${SERVICE}.service.d
+	mkdir -p $OVERRIDE_DIR
 
-  cat << OVERRIDE > ${OVERRIDE_DIR}/override.conf
+	cat << OVERRIDE > ${OVERRIDE_DIR}/override.conf
 [Service]
 PrivateTmp=no
 OVERRIDE
